GET http://localhost:3000/recipeList/retrieve/MasonJarLanterns HTTP/1.1

###

GET http://localhost:3000/recipeList/retrieve/WineBottleLights HTTP/1.1

###
GET http://localhost:3000/recipeList/retrieve/PillowOutofaShirt HTTP/1.1